### PR TITLE
Fix Siemens ASCCONV header parsing

### PR DESCRIPTION
**Pull request by matthew-brett**
Use version of Nibabel ASCCONV parsing for Siemens CSA header.

There are some changes here - hoping you're OK with them.

Your parser stripped the type information from the front of the variable names
in the ASCCONV header, but I chose not to do that.  I think that's desirable
because it's easier to see the relationship between the values and the text of
the file, but I believe we have to preserve the prefixes, because the system sometimes uses
variables that differ only in the type prefix.  See the `ascconv.py` file for
details, but the example given there is:

    sWipMemBlock.tFree	 = 	""WIP_Identifier: WIP#919B(Fri Feb 10 09:46:48 2017)""
    sWipMemBlock.alFree[0]	 = 	2

There are some other difference in parsing.  To make it easier to see what's
going on, I've dumped the CSA out to a JSON file for testing:
`tests/files/csa.json` instead of `csa.pickle`.  The current file is the result
of the new parsing. I'll attach the result of the old parsing to make it easier
to do a diff.

The parsing is pretty quick, I think.

### CODE REVIEW

**Comment by matthew-brett** [comment]
Previous parsing output in JSON for comparision with `tests/files/csa.json` :
[orig_csa.json.txt](https://github.com/open-dicom/dicom_parser/files/8097960/orig_csa.json.txt)

**Comment by matthew-brett** [comment]
I felt the need for a benchmark.  Do you have some way of running benchmarks?

The thing I used was:

```python
# Benchmark CSA parsing

import timeit

from dicom_parser.utils.siemens.csa.header import CsaAsciiHeader

from tests.fixtures import TEST_EP2D_IMAGE_PATH

with open(TEST_EP2D_IMAGE_PATH, 'rb') as fobj:
    dcm_bytes = fobj.read()

hdr = CsaAsciiHeader(dcm_bytes)

res = timeit.timeit('CsaAsciiHeader(dcm_bytes).parse()',
                    number=100,
                    globals=globals())
print(res)
```

This gave me timings of about 33ms / run on `master` and about 49ms / run on this branch.

That may be worth it, as I think the parsing is more correct here - but your call.

Thinking about ways to speed it up - I could imagine doing something like walking through the Python AST (see [nice tutorial](https://greentreesnakes.readthedocs.io)), and using that to:

a) Check that code only ever does simple assignment with literals, to avoid security risks.
b) Create object hierarchy for assignment

and then just execute the AST to do the assignment.    That would likely be a fair bit quicker.

**Comment by ZviBaratz** [comment]
I wasn't aware of the significance of the prefixes. I'm glad it's resolved and I definitely prefer this implementation. I'm sure if it proves to be an issue (and also if doesn't) we can find ways to make it more efficient. 

I'm creating a PR to your PR's branch so I can push some minor suggestions.

**Comment by matthew-brett** [comment]
Further investigation shows that there isn't much room for optimization with this approach because profiling (see below) gives these top 4 calls

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.053    0.053    0.053    0.053 {built-in method builtins.compile}
     2250    0.009    0.000    0.013    0.000 ascconv.py:63(assign2atoms)
     2250    0.008    0.000    0.016    0.000 ascconv.py:144(obj_from_atoms)
55937/49670    0.006    0.000    0.008    0.000 {built-in method builtins.isinstance}
```

In other words, the main time is in the Python AST parsing routine (in C).   I thought of various ways to make the parsing lazy, which might be worth implementing.   Or, maybe this could be the for-now solution, defining correct parsing, and a later PR could implement the same parsing in a faster way.

Profiling script:

```python
# Benchmark CSA parsing

import cProfile

from dicom_parser.utils.siemens.csa.header import CsaAsciiHeader

from tests.fixtures import TEST_EP2D_IMAGE_PATH

with open(TEST_EP2D_IMAGE_PATH, 'rb') as fobj:
    dcm_bytes = fobj.read()

hdr = CsaAsciiHeader(dcm_bytes)

print(cProfile.run('hdr.parse()', sort='time'))
```

**Comment by ZviBaratz** [comment]
>  Or, maybe this could be the for-now solution, defining correct parsing, and a later PR could implement the same parsing in a faster way.

I prefer this approach, but if you already have something in mind and would like to give it a go, I get that.

**Comment by matthew-brett** [comment]
If you're happy to merge this - that's fine with me.   Later I might have a
go at working up a lazy evaluation interface as a separate PR ...

**Pull request merged**
